# Generated by Django 5.2.14 on 2026-05-19 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Physician', '0001_initial'),
        ('accounts', '0003_useraccessmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssayMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assay_code', models.CharField(max_length=20, unique=True)),
                ('assay_name', models.CharField(max_length=150)),
                ('sample_type', models.CharField(max_length=50)),
                ('tat_hours', models.SmallIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('normal_range', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assay_master',
            },
        ),
        migrations.CreateModel(
            name='TestMenuMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_code', models.CharField(max_length=20, unique=True)),
                ('menu_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'test_menu_master',
            },
        ),
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=20, unique=True)),
                ('ordered_at', models.DateTimeField()),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('order_status', models.SmallIntegerField(choices=[(1, 'Ordered'), (2, 'Collected'), (3, 'In-Lab'), (4, 'Completed')], default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(blank=True, db_column='collected_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_collected', to='accounts.usermaster')),
                ('ordered_by', models.ForeignKey(db_column='ordered_by', on_delete=django.db.models.deletion.CASCADE, related_name='orders_placed', to='accounts.usermaster')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Physician.patientmaster')),
                ('received_by', models.ForeignKey(blank=True, db_column='received_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_received', to='accounts.usermaster')),
            ],
            options={
                'db_table': 'order_transaction',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=40, null=True)),
                ('normal_range', models.CharField(blank=True, max_length=100, null=True)),
                ('flag', models.CharField(blank=True, max_length=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('entered_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assay', models.ForeignKey(db_column='assay_id', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='LabTechnician.assaymaster')),
                ('entered_by', models.ForeignKey(db_column='entered_by', on_delete=django.db.models.deletion.CASCADE, related_name='results_entered', to='accounts.usermaster')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='LabTechnician.ordertransaction')),
                ('verified_by', models.ForeignKey(blank=True, db_column='verified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_verified', to='accounts.usermaster')),
            ],
            options={
                'db_table': 'results',
            },
        ),
        migrations.AddField(
            model_name='assaymaster',
            name='menu',
            field=models.ForeignKey(db_column='menu_id', help_text='References test_menu_master — parent test category', on_delete=django.db.models.deletion.CASCADE, related_name='assays', to='LabTechnician.testmenumaster'),
        ),
    ]
